MCPODS-6503 gradle, vert.x and retry

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -41,11 +41,12 @@ jobs:
         with:
           distribution: 'temurin'
           java-version: '17'
-      - name: Setup Gradle, execute tests & verify overall coverage
+      - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
         with:
-          arguments: test jacocoTestReport jacocoTestCoverageVerification
           gradle-version: 8.2
+      - name: Execute tests & verify overall coverage
+        run: gradle test jacocoTestReport jacocoTestCoverageVerification
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
@@ -62,6 +63,6 @@ jobs:
           title: Code Coverage
       - name: Fail when coverage of changed files is too low
         run: |
-            CHANGED_FILES_FAILED=$(echo '${{ steps.jacoco.outputs.coverage-changed-files }} < ${{ env.MIN_COVERAGE_CHANGED_FILES }}' | bc)
-            [[ $CHANGED_FILES_FAILED -ne 0 ]] && echo 'Changed files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}% is smaller than required ${{ env.MIN_COVERAGE_CHANGED_FILES }}%'
-            [[ $CHANGED_FILES_FAILED -ne 0 ]] && exit 1 || exit 0
+          CHANGED_FILES_FAILED=$(echo '${{ steps.jacoco.outputs.coverage-changed-files }} < ${{ env.MIN_COVERAGE_CHANGED_FILES }}' | bc)
+          [[ $CHANGED_FILES_FAILED -ne 0 ]] && echo 'Changed files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}% is smaller than required ${{ env.MIN_COVERAGE_CHANGED_FILES }}%'
+          [[ $CHANGED_FILES_FAILED -ne 0 ]] && exit 1 || exit 0
